### PR TITLE
Readme file created

### PR DESCRIPTION
**Pull request by anantbharti**

### CODE REVIEW

**Review by ashwanijha04 — CHANGES_REQUESTED** [review]
Could you please use markdown to make it more readable and host it on GitHub pages.

We need a section for each topic. 
The topics would be 
Arrays
Trees etc
(Check the other open issue for creating directories for a list of topics)

**Comment by ashwanijha04** [comment]
hi @anantbharti 
Are you working on it?

**Comment by anantbharti** [comment]
Yes I am working on it.

**Comment by anantbharti** [comment]
Changes done! Ask if more changes required and please merge it.

**Comment by ashwanijha04** [comment]
Thanks @anantbharti 
I'll merge this. Would you like to work on creating GitHub pages to host this in an elegant way?
I can create another issue for you.

Closing this. Thanks for the help

**Comment by ashwanijha04** [comment]
I don't see changes in the readme.
Reopening.

**Comment by anantbharti** [comment]
@ashwanijha04  But I have made a lot of changes. There may be some other issue. I want to do this. Please let me do it. And please add hacktoberfest-accepted label as I am participating in it

**Pull request merged**
